// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaK5pWyl58_J0F_Xub6J36nFYVqrqzM-E',
    appId: '1:1061257437917:web:068437a68d5161cb9cf134',
    messagingSenderId: '1061257437917',
    projectId: 'servicernew',
    authDomain: 'servicernew.firebaseapp.com',
    storageBucket: 'servicernew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0BKdrrwEtAqcIZFqPtuhayPAbI0D4f4',
    appId: '1:1061257437917:android:61548f63141504219cf134',
    messagingSenderId: '1061257437917',
    projectId: 'servicernew',
    storageBucket: 'servicernew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96-fKVntXoKxuPoNLeX-Pgq6D9KT6sKs',
    appId: '1:1061257437917:ios:f7e2a4e4051f20009cf134',
    messagingSenderId: '1061257437917',
    projectId: 'servicernew',
    storageBucket: 'servicernew.appspot.com',
    iosBundleId: 'com.example.servicer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96-fKVntXoKxuPoNLeX-Pgq6D9KT6sKs',
    appId: '1:1061257437917:ios:c57b1c05dd93a0989cf134',
    messagingSenderId: '1061257437917',
    projectId: 'servicernew',
    storageBucket: 'servicernew.appspot.com',
    iosBundleId: 'com.example.servicer.RunnerTests',
  );
}
